### ISSUE TITLE
Crashes when it sees a face

### ISSUE THREAD

**Issue by rsingh2083** [AaronFan1992/jetson_nano_demo#12]
As soon as someone comes near the camera, it crashes with this error :-

Traceback (most recent call last):
  File "camera_demo.py", line 201, in <module>
    main()
  File "camera_demo.py", line 181, in main
    if dict[0][1] > VERIFICATION_THRESHOLD:
IndexError: list index out of range

**Comment by rsingh2083** [comment]
Solved it by creating the face_db folder and then pasting a sample face photo in it
