### ISSUE TITLE
Error when running on Jetson Nano

### ISSUE THREAD

**Issue by yichengye310** [AaronFan1992/jetson_nano_demo#2]
I am using Numpy 1.16.4.
```
Traceback (most recent call last):
  File "camera_demo.py", line 10, in <module>
    from utils import face_preprocess
  File "/home/yichengye/Desktop/jetson_nano_demo/face_recognition/utils/face_preprocess.py", line 4, in <module>
    from skimage import transform as trans
  File "/usr/lib/python3/dist-packages/skimage/__init__.py", line 158, in <module>
    from .util.dtype import *
  File "/usr/lib/python3/dist-packages/skimage/util/__init__.py", line 7, in <module>
    from .arraycrop import crop
  File "/usr/lib/python3/dist-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'

```

**Comment by yichengye310** [comment]
1.17.0 also has the same issue. Which version are you using please?

**Comment by yichengye310** [comment]
It might be an issue with skimage. I am using 0.13.1, trying to upgrade.

**Comment by yichengye310** [comment]
Update skimage to 1.16.0 solves the problem.
