### ISSUE TITLE
REport error when run camera_demo.py on jetson nano

### ISSUE THREAD

**Issue by agunin** [AaronFan1992/jetson_nano_demo#8]
jetson@jetson-desktop:~/Downloads/jetson_nano_demo-master/face_recognition$ sudo python3 camera_demo.py 
2019-12-27 15:50:29.284513: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
Traceback (most recent call last):
  **File "camera_demo.py", line 10, in <module>
    from utils import face_preprocess**
  File "/home/jetson/Downloads/jetson_nano_demo-master/face_recognition/utils/face_preprocess.py", line 4, in <module>
    from skimage import transform as trans
  File "/usr/local/lib/python3.6/dist-packages/skimage/transform/__init__.py", line 2, in <module>
    from .hough_transform import (hough_line, hough_line_peaks,
  File "/usr/local/lib/python3.6/dist-packages/skimage/transform/hough_transform.py", line 2, in <module>
    from ._hough_transform import (_hough_circle,
  File "skimage/transform/_hough_transform.pyx", line 13, in init skimage.transform._hough_transform
  File "/usr/local/lib/python3.6/dist-packages/skimage/draw/__init__.py", line 5, in <module>
    from .draw3d import ellipsoid, ellipsoid_stats
  File "/usr/local/lib/python3.6/dist-packages/skimage/draw/draw3d.py", line 2, in <module>
    from scipy.special import (ellipkinc as ellip_F, ellipeinc as ellip_E)
  File "/usr/lib/python3/dist-packages/scipy/special/__init__.py", line 648, in <module>
    from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal
  File "/usr/lib/python3/dist-packages/scipy/special/_ellip_harm.py", line 7, in <module>
    from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
**ImportError: cannot import name '_ellipsoid'**

My pip3 list is following

etson@jetson-desktop:~/Downloads/jetson_nano_demo-master/face_recognition$ pip3 list
Package                       Version            
----------------------------- -------------------
absl-py                       0.9.0              
apt-clone                     0.2.1              
apturl                        0.5.2              
asn1crypto                    0.24.0             
astor                         0.8.1              
attrs                         17.4.0             
beautifulsoup4                4.6.0              
blinker                       1.4                
Brlapi                        0.6.6              
cachetools                    4.0.0              
certifi                       2018.1.18          
chardet                       3.0.4              
Click                         7.0                
cryptography                  2.1.4              
cupshelpers                   1.0                
cycler                        0.10.0             
decorator                     4.4.1              
defer                         1.0.6              
distro-info                   0.18ubuntu0.18.04.1
dlib                          19.17.0            
face-recognition              1.2.3              
face-recognition-models       0.3.0              
feedparser                    5.2.1              
gast                          0.2.2              
google-auth                   1.10.0             
google-auth-oauthlib          0.4.1              
google-pasta                  0.1.8              
graphsurgeon                  0.4.1              
grpcio                        1.26.0             
h5py                          2.10.0             
html5lib                      0.999999999        
httplib2                      0.9.2              
idna                          2.6                
imageio                       2.6.1              
joblib                        0.11               
Keras-Applications            1.0.8              
Keras-Preprocessing           1.1.0              
keyring                       10.6.0             
keyrings.alt                  3.0                
language-selector             0.1                
launchpadlib                  1.10.6             
lazr.restfulclient            0.13.5             
lazr.uri                      1.0.3              
louis                         3.5.0              
lxml                          4.2.1              
macaroonbakery                1.1.3              
Mako                          1.0.7              
Markdown                      3.1.1              
MarkupSafe                    1.0                
matplotlib                    2.1.1              
mock                          3.0.5              
networkx                      2.4                
nose                          1.3.7              
numpy                         1.18.0             
oauth                         1.0.1              
oauthlib                      3.1.0              
olefile                       0.45.1             
opt-einsum                    3.1.0              
PAM                           0.4.2              
pbr                           5.4.4              
Pillow                        6.2.1              
pip                           19.3.1             
pluggy                        0.6.0              
portpicker                    1.3.1              
protobuf                      3.11.2             
psutil                        5.6.7              
py                            1.5.2              
py-cpuinfo                    5.0.0              
pyasn1                        0.4.8              
pyasn1-modules                0.2.7              
pycairo                       1.16.2             
pycrypto                      2.6.1              
pycups                        1.9.73             
pygobject                     3.26.1             
PyICU                         1.9.8              
PyJWT                         1.5.3              
pymacaroons                   0.13.0             
PyNaCl                        1.1.2              
pyparsing                     2.2.0              
pyRFC3339                     1.0                
pytest                        3.3.2              
python-apt                    1.6.4              
python-dateutil               2.6.1              
python-debian                 0.1.32             
pytz                          2018.3             
PyWavelets                    0.5.1              
pyxdg                         0.25               
PyYAML                        3.12               
requests                      2.22.0             
requests-oauthlib             1.3.0              
requests-unixsocket           0.1.5              
rsa                           4.0                
scikit-image                  0.16.2             
scikit-learn                  0.19.1             
scipy                         0.19.1             
SecretStorage                 2.3.1              
setuptools                    42.0.2             
simplejson                    3.13.2             
six                           1.13.0             
ssh-import-id                 5.7                
system-service                0.3                
systemd-python                234                
tensorboard                   2.0.2              
tensorflow-estimator          2.0.1              
tensorflow-gpu                2.0.0+nv19.12.tf2  
tensorrt                      5.1.6.1            
termcolor                     1.1.0              
testresources                 2.0.1              
ubuntu-drivers-common         0.0.0              
uff                           0.6.3              
unity-scope-calculator        0.1                
unity-scope-chromiumbookmarks 0.1                
unity-scope-colourlovers      0.1                
unity-scope-devhelp           0.1                
unity-scope-firefoxbookmarks  0.1                
unity-scope-manpages          0.1                
unity-scope-openclipart       0.1                
unity-scope-texdoc            0.1                
unity-scope-tomboy            0.1                
unity-scope-virtualbox        0.1                
unity-scope-yelp              0.1                
unity-scope-zotero            0.1                
urllib3                       1.22               
wadllib                       1.3.2              
webencodings                  0.5                
Werkzeug                      0.16.0             
wheel                         0.33.6             
wrapt                         1.11.2             
xkit                          0.0.0              
zope.interface                4.3.2  

Can you help me?

Thanks!

**Comment by muhammadabdullah34907** [comment]
Some issue can be simply resolved if you google it.

https://stackoverflow.com/questions/44159136/sklearn-cannot-import-name-ellipsoid
